-- 书籍难度统计表
CREATE TABLE IF NOT EXISTS book_difficulty (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '自增ID',
    book_name VARCHAR(255) NOT NULL COMMENT '书名',
    author VARCHAR(100) DEFAULT NULL COMMENT '作者名',
    char_types INT COMMENT '字种数',
    char_types_in_1500 INT COMMENT '前1500内字种数',
    char_types_out_1500 INT COMMENT '前1500外字种数',
    coverage_500 DECIMAL(5,2) COMMENT '前500字覆盖率(%)',
    coverage_1000 DECIMAL(5,2) COMMENT '前1000字覆盖率(%)',
    coverage_1500 DECIMAL(5,2) COMMENT '前1500字覆盖率(%)',
    avg_order_95 DECIMAL(8,2) COMMENT '95%平均字序',
    avg_order_99 DECIMAL(8,2) COMMENT '99%平均字序',
    chars_95 INT COMMENT '95%覆盖字数',
    chars_99 INT COMMENT '99%覆盖字数',
    chars_95_in_1500 INT COMMENT '95%覆盖字数(前1500内)',
    chars_95_out_1500 INT COMMENT '95%覆盖字数(前1500外)',
    chars_99_in_1500 INT COMMENT '99%覆盖字数(前1500内)',
    chars_99_out_1500 INT COMMENT '99%覆盖字数(前1500外)',
    difficulty_score DECIMAL(5,2) COMMENT '难度得分(0-100)',
    star_level VARCHAR(20) COMMENT '星级(⭐-⭐⭐⭐⭐⭐)',
    file_name VARCHAR(255) COMMENT '原始文件名',
    total_chars INT COMMENT '总字符数',
    rare_char_types INT COMMENT '生僻字字种数',
    rare_char_ratio DECIMAL(5,2) COMMENT '生僻字占比(%)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    INDEX idx_book_name (book_name),
    INDEX idx_author (author),
    INDEX idx_difficulty (difficulty_score),
    INDEX idx_star_level (star_level),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍难度统计表';
